### ISSUE TITLE
Build all MVP pages (basic UI)

### ISSUE THREAD

**Issue by AndyDupuis** [AndyDupuis/fitnesstrack#2]
**Task Report**

**Description:** all basic landing pages for the web app need to be built, just the html and css, no functionality yet. They should be responsive though, follow the colour/design theme, and look nice.

**Includes:** 

- [ ] Home page
- [ ] Login / Signup pages
- [ ] Contact Us page
- [ ] Goals page (this is the landing page for once the user has logged in)
- [ ] Food page
- [ ] Workouts page
- [ ] Weight page

**Colour/design Theme:** 

Main Colours:
- #32D9CB
- #205072
- black and white

Buttons Style: 

<img width="95" alt="image" src="https://user-images.githubusercontent.com/54333765/102082170-dc700280-3de7-11eb-8a6c-1a97edf666ac.png">

on Mouse-over
<img width="103" alt="image" src="https://user-images.githubusercontent.com/54333765/102082206-eb56b500-3de7-11eb-977c-37dc68d9d976.png">

**Comment by AndyDupuis** [comment]
Home page, Login and Signup pages, and Contact page are done
